#!/usr/bin/env bash
#
# analyze-commit-style.sh
# Analyzes recent commit history to extract commit message patterns
#
# Usage: ./analyze-commit-style.sh [number_of_commits]
#
# Outputs a commit-style.md file with discovered patterns

set -euo pipefail

# Number of commits to analyze (default: 50)
NUM_COMMITS="${1:-50}"

# Check if we're in a git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo "Error: Not in a git repository" >&2
    exit 1
fi

# Get recent commit messages
COMMITS=$(git log --format="%s" -n "$NUM_COMMITS" 2>/dev/null || echo "")

if [ -z "$COMMITS" ]; then
    echo "Error: No commits found in repository" >&2
    exit 1
fi

# Extract patterns
echo "Analyzing $NUM_COMMITS recent commits..."

# Find tags (anything in square brackets or before colons)
TAGS=$(echo "$COMMITS" | grep -Eo '^\[[^]]+\]|^[a-z]+:' | sort | uniq -c | sort -rn || true)

# Find common verbs (first word after tags)
VERBS=$(echo "$COMMITS" | sed -E 's/^\[[^]]+\] //;s/^[a-z]+: //' | awk '{print $1}' | sort | uniq -c | sort -rn | head -20 || true)

# Analyze message length
AVG_LENGTH=$(echo "$COMMITS" | awk '{ total += length($0); count++ } END { if (count > 0) print int(total/count); else print 0 }')

# Check for common patterns
HAS_TAGS=$(echo "$COMMITS" | grep -c '^\[' 2>/dev/null || echo "0")
HAS_TAGS=${HAS_TAGS//[^0-9]/}
HAS_CONVENTIONAL=$(echo "$COMMITS" | grep -cE '^(feat|fix|docs|style|refactor|test|chore|perf|ci|build|revert):' 2>/dev/null || echo "0")
HAS_CONVENTIONAL=${HAS_CONVENTIONAL//[^0-9]/}
HAS_IMPERATIVE=$(echo "$COMMITS" | grep -cE '^[A-Z][a-z]+ ' 2>/dev/null || echo "0")
HAS_IMPERATIVE=${HAS_IMPERATIVE//[^0-9]/}

# Determine dominant style
TOTAL=$(echo "$COMMITS" | wc -l | tr -d ' ')
if [ "$TOTAL" -eq 0 ]; then
    TAG_PERCENT=0
    CONVENTIONAL_PERCENT=0
    IMPERATIVE_PERCENT=0
else
    TAG_PERCENT=$((HAS_TAGS * 100 / TOTAL))
    CONVENTIONAL_PERCENT=$((HAS_CONVENTIONAL * 100 / TOTAL))
    IMPERATIVE_PERCENT=$((HAS_IMPERATIVE * 100 / TOTAL))
fi

echo "Pattern analysis complete."
echo "- Tags in brackets: $TAG_PERCENT%"
echo "- Conventional commits: $CONVENTIONAL_PERCENT%"
echo "- Imperative mood: $IMPERATIVE_PERCENT%"
echo ""

# Generate commit-style.md
cat > commit-style.md <<EOF
# Commit Style Guide

This file was auto-generated by analyzing the last $NUM_COMMITS commits.
Last updated: $(date +"%Y-%m-%d %H:%M:%S")

## Detected Patterns

### Format Style
EOF

if [ "$CONVENTIONAL_PERCENT" -gt 50 ]; then
    cat >> commit-style.md <<EOF
- **Primary style**: Conventional Commits (${CONVENTIONAL_PERCENT}%)
- Use format: \`type: description\` or \`type(scope): description\`
EOF
elif [ "$TAG_PERCENT" -gt 50 ]; then
    cat >> commit-style.md <<EOF
- **Primary style**: Bracketed tags (${TAG_PERCENT}%)
- Use format: \`[tag] description\`
EOF
else
    cat >> commit-style.md <<EOF
- **Primary style**: Free-form (mixed patterns detected)
- No dominant style found. Follow imperative mood convention.
EOF
fi

cat >> commit-style.md <<EOF

### Message Length
- Average first line: $AVG_LENGTH characters
- Recommended max: 72 characters

### Common Tags/Types
EOF

echo "$TAGS" | head -15 | while read -r count tag; do
    echo "- \`$tag\` ($count occurrences)" >> commit-style.md
done

cat >> commit-style.md <<EOF

### Common Starting Verbs
EOF

echo "$VERBS" | head -10 | while read -r count verb; do
    echo "- \`$verb\` ($count times)" >> commit-style.md
done

cat >> commit-style.md <<EOF

## Examples from This Repository

Recent commits following the detected style:

\`\`\`
$(echo "$COMMITS" | head -10)
\`\`\`

## Guidelines

Based on the analysis:

1. **First line**: Keep under 72 characters
2. **Style**: Follow the primary style detected above
3. **Verbs**: Use common verbs from this project's history
4. **Consistency**: Match the patterns used in recent commits

## Regenerating This File

To update this guide based on new commits:

\`\`\`bash
./analyze-commit-style.sh [number_of_commits]
\`\`\`

Default analyzes the last 50 commits.
EOF

echo "✓ Created commit-style.md"
echo ""
echo "Review the generated file and edit if needed:"
echo "  cat commit-style.md"
